name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
      - run: npm ci
      - run: npm test

  test1:
    needs: [lint]
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
      - run: npm ci
      - run: npm test

  test2:
    needs: [lint]
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
      - run: npm ci
      - run: npm test

  test3:
    needs: [lint]
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  build:
    needs: [lint, test1, test2, test3]
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
